### PR TITLE
Fixed usage of autowire annotations in traits

### PR DESCRIPTION
**Pull request by enumag**
You might want to wait with merging this until nette 2.3 is out.

### CODE REVIEW

**Comment by enumag** [comment]
Travis failed because of current DDos attack on GitHub. I've run the tests for both Nette 2.2 and Nette 2.3 manually and thay're ok. The new feature is available for Nette 2.3 only, the test is skipped for Nette 2.2.

**Comment by enumag** [comment]
ping @fprochazka

**Comment by fprochazka** [comment]
Dammit, forgot about this one... Thank you!

**Comment by enumag** [comment]
Thx! :-)

**Pull request closed without merging**
